version: 2


jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.4.0
      - image: sudix/docker-dynamo-local


    steps:
      - checkout


      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}


      - run: yarn install --pure-lockfile


      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules


      - run: yarn lint


      - run:
          name: Run tests
          environment:
            DYNAMO_ENDPOINT: http://dynamo:8000
            DYNAMO_REGION: us-west-2
          command: yarn test
